// Generated by 'just _gen-scanner-indices'. Do not edit by hand.
// Source: src/parser.c (ts_external_scanner_symbol_identifiers).
#ifndef DAML_SCANNER_INDICES_H
#define DAML_SCANNER_INDICES_H
#define DAML_SYM_CMD_LAYOUT_START 2
#define DAML_SYM_TYPE_APPLY_GUARD 49
#define DAML_SYM_IN_EXP_WITH 50
#endif
