name: Formatting

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  SQLX_OFFLINE: "true"

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@9adf02b41cfdac2632e1c16f0480ff5bf3b05dd6 # v3.21.1
      - name: Run pre-commit checks via devshell
        run: nix develop --accept-flake-config .# --command just pre-commit
